name: olearistest
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter
  # l10n
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

  # navigation
  auto_route: 10.1.2

  # Dependency Injection
  get_it: ^8.0.3
  injectable: ^2.5.0

  #state management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  #network
  dio: ^5.8.0+1
  dio_http_formatter: ^3.3.0
  http_parser: ^4.1.2

  #helpers
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  logger: ^2.6.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0



  #UI
  another_flushbar: ^1.12.30
  cupertino_icons: ^1.0.8


  #database
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  auto_route_generator: 10.2.4
  injectable_generator: ^2.7.0
  freezed: ^3.0.6
  flutter_gen_runner:


flutter_gen:
  output: lib/generated/
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true

flutter_intl:
  main_locale: en
  enabled: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/


